### ISSUE TITLE
Remove <tour> wrapping requirement

### ISSUE THREAD

**Issue by kentcdodds** [DaftMonk/angular-tour#10]
This is awesome. I don't have a current use case for it, but I know that when I do I'm not going to want to wrap everything in a `<tour>` is there any way that requirement can be lifted? The thing is, I don't have a page so I can have a tour. Integrating the tour should be as lightweight as possible I think, and by requiring everything to be wrapped in a specific element it's imposing itself on what really matters (the actual page markup). Thoughts?

**Comment by lvarayut** [comment]
I'm facing the same problem. I had to wrap everything inside the `<tour>` element which causes maintainability issues.

**Comment by dbounds** [comment]
@DaftMonk did anything ever come of this? I really like @kentcdodds's suggestion and very much dislike the idea of wrapping everything in <tour>.

**Comment by dshep4** [comment]
You can use virtual steps to get around this
