### ISSUE TITLE
iOS 7 Scrolling issue

### ISSUE THREAD

**Issue by Sljubura** [DaftMonk/angular-tour#29]
Hi, I got bad flickering and unsuccessful scroll when tour tries to scroll on iOS (iPhone 5s iOS 7). 
I found out that the cause is the: 
line 305: scrollLeft: target.offset().left + offsetX

Removing that line and just leaving scrollTop solved it.

**Comment by booleanbetrayal** [comment]
Not seeing this in latest master. Please take a look @Sljubura . Can re-open if needed.
