### ISSUE TITLE
Can't seem to be able to run it

### ISSUE THREAD

**Issue by solenoo** [DaftMonk/angular-tour#35]
Hi for some reason I'm having trouble to start the tour to work.

HTML

```
<tour step="currentStep">
<header tourtip="tip 1" tourtip-next-label="Learn more" tourtip-placement="bottom" tourtip-offset="60" tourtip-step="0">
.
.
.
</header>
<aside tourtip="tip 2" tourtip-next-label="Learn more" tourtip-placement="right" tourtip-offset="60" tourtip-step="1">
.
.
.
</aisde>
</tour>
```
JS

```
$scope.currentStep = 0;
```

And nothing happens. What am I missing ?

**Comment by jermspeaks** [comment]
Is it at all related to this? I'm getting an error from this line
```js
if (scope.ttAnimation)
              tourtip.fadeIn();
```

**Comment by booleanbetrayal** [comment]
@jermspeaks - is this issue still valid? Do you have jQuery loaded prior to angular-tour?

**Comment by jermspeaks** [comment]
I'm unsure. I decided not to use this library in the end, and I'm not working on that project that used it anymore.

**Comment by rinogo** [comment]
I can confirm that the problem was almost certainly that jQuery wasn't loaded.  It wasn't loaded in our app and I got an error about `fadeIn` being undefined.  Loading jQuery fixed the problem.
