### ISSUE TITLE
Loading order of Angular and JQuery

### ISSUE THREAD

**Issue by tanjabrzak** [DaftMonk/angular-tour#48]
I noticed that the directive does not work if the Angular loading before JQuery (which is the case in my app). Is there a way not to change load ordering in my app and still get directive to work?

**Comment by dmackerman** [comment]
Why would you load Angular before jQuery? Just curious if it's a requirement for your app?

**Comment by thoughtspacewebsites** [comment]
Wow, this fixed an issue I was having. This should probably be noted more clearly in the documentation, considering this is one of the few Angular modules I've found that has this stipulation.

**Comment by booleanbetrayal** [comment]
added a little note, while jQuery is still around.
