### ISSUE TITLE
Bower main attribute is missing reference to css file

### ISSUE THREAD

**Issue by david-meza** [DaftMonk/angular-tour#64]
This should be an easy fix. I'll try to do the PR myself. Essentially the `bower.json` file should be changed to

    "main": [
      "./dist/angular-tour-tpls.min.js",
      "./dist/angular-tour.css"
    ],

as opposed to what it is now

    "main": "./dist/angular-tour-tpls.min.js",

Why is this important? When you run automated tasks like Grunt's `wiredep` it looks at this attribute to automatically generate your `link` and `script` tags, and the absence of it forces you to manually add the missing `link` tag every time a task runs.

**Comment by booleanbetrayal** [comment]
Thanks!

**Comment by david-meza** [comment]
Merge #65 fixes this.
