### ISSUE TITLE
Getting "undefined is not a function" error messages

### ISSUE THREAD

**Issue by GillesDebunne** [DaftMonk/angular-tour#9]
I installed and copy pasted the sample code in my project (jquery 2.1.1, angular 1.2.16). I get "undefined is not a function" error messages in the console, for the 'hide' and 'show' methods, where 'detach()' and 'fadein()' are applied to the tourtip variable. This var is the result of a $compile defined above, and is indeed non null.

I didn't investigate any further, and the error may well be on my side. Just in case others bump into the same issue.

**Comment by booleanbetrayal** [comment]
There's an open PR (#21) for removing the jQuery dependencies entirely. Going to go ahead and close this and will update the docs.
